/**
 * Ask Wakili grounding data — generated from case-digest-index.json plus the
 * facts/holding and practice-point text already published on each case note
 * page. This is a snapshot, not a live read of the JSON/HTML at request time —
 * regenerate it (see ASK-WAKILI-BUILD.md) whenever the Case Digest changes, so
 * Ask Wakili never cites a case that was pulled or drifts from what the site
 * itself says about a matter.
 *
 * Every "why" the model writes must trace to a case in this exact list — the
 * function enforces that server-side (see ask-wakili.mts) by discarding any
 * id in the model's response that is not a key of CASEBANK_BY_ID below.
 */

export interface CasebankEntry {
  id: string;
  name: string;
  citation: string;
  year: string;
  url: string;
  outcome: string;
  categories: string[];
  summary: string;
  practicePoint: string;
}

export const CASEBANK: CasebankEntry[] = [
  {
    id: "balicha-v-platinum-credit-limited",
    name: "Balicha v Platinum Credit Limited",
    citation: "[2026] KEHC 4735",
    year: "2026",
    url: "https://dataprivacyadvocates.co.ke/case-balicha-v-platinum-credit-limited.html",
    outcome: "Preliminary objection overruled",
    categories: ["Data Protection", "Administrative Law"],
    summary: "A police officer sued after his salary was wrongly deducted for a loan he never took, adding claims of unlawful collection of his passport photo, ID, salary details and M-Pesa statements. The lender later objected that only the Data Commissioner had original jurisdiction over such claims. The Court didn't reach that question on the merits, because the lender's own defence had admitted the Court's jurisdiction in an earlier paragraph \u2014 a party cannot take an inconsistent factual position in the same suit without amending its pleadings first. The Court added, independently, that a claim combining constitutional and common-law wrongs with a Data Protection Act element is not \"purely statutory\" and survives on that basis too.",
    practicePoint: "Never plead an admission of jurisdiction as a fallback position \u2014 it can be used to defeat a jurisdictional objection you later need to raise.",
  },
  {
    id: "barasa-v-csi-energy-group-limited",
    name: "Barasa v CSI Energy Group Limited",
    citation: "[2026] KEHC 3274",
    year: "2026",
    url: "https://dataprivacyadvocates.co.ke/case-barasa-v-csi-energy-group-limited.html",
    outcome: "Petition dismissed",
    categories: ["Data Protection", "Administrative Law"],
    summary: "A former employee complained that his employer kept his image on its website and marketing platforms after his resignation, causing emotional distress. The employer said it removed the material promptly on notice and had acted in good faith. The Court did not reach the merits: the petitioner had never lodged a complaint with the ODPC before going straight to a constitutional petition, and the core of the grievance was a data protection complaint squarely within the ODPC's mandate. The Court declined jurisdiction on the doctrine of exhaustion.",
    practicePoint: "However sympathetic the facts, a data protection grievance that has never touched the ODPC is not yet ripe for a constitutional petition \u2014 file the complaint first, and keep the petition in reserve for genuine gaps in the ODPC's remedies.",
  },
  {
    id: "bore-v-alliance-leasing-limited-and-another",
    name: "Bore v Alliance Leasing Limited & Another",
    citation: "[2026] KEHC 3191",
    year: "2026",
    url: "https://dataprivacyadvocates.co.ke/case-bore-v-alliance-leasing-limited-and-another.html",
    outcome: "Preliminary objection dismissed",
    categories: ["Data Protection", "Administrative Law"],
    summary: "Facing a petition alleging covert surveillance, unauthorised access to M-Pesa and bank records, and adverse decisions taken without notice, the respondent argued the whole dispute should have gone to the ODPC first under Sections 8, 9, 56 and 57 of the Act. The Court held that whether a dispute is \"purely statutory\" or genuinely constitutional cannot be decided on the pleadings alone at a preliminary stage, and \u2014 critically \u2014 that the Data Commissioner simply cannot grant some of the relief being sought: the ODPC cannot interpret the Constitution, issue permanent injunctions, or award general damages for constitutional violations. Where those are the actual reliefs sought, exhaustion doesn't apply.",
    practicePoint: "If the relief sought (a permanent injunction, general damages, a constitutional declaration) is something the ODPC has no power to grant, a preliminary objection based on exhaustion is unlikely to succeed.",
  },
  {
    id: "chege-v-sholei",
    name: "Chege v Sholei",
    citation: "[2026] KEHC 3911",
    year: "2026",
    url: "https://dataprivacyadvocates.co.ke/case-chege-v-sholei.html",
    outcome: "Petition dismissed",
    categories: ["Data Protection", "Administrative Law"],
    summary: "A petitioner alleged her private phone messages had been accessed without authorisation and used as evidence in a separate Succession Cause, in breach of Article 31. The Court held the real dispute was the admissibility of that evidence in the Succession Cause \u2014 a question for the Succession Court, by appeal or review, not a fresh constitutional petition running in parallel. Allowing the petition to proceed would have undermined the finality of the Succession proceedings by attacking them collaterally.",
    practicePoint: "Not every privacy grievance is a constitutional question. Where a properly seized court has already ruled, or is seized, of the underlying evidentiary dispute, the doctrine of constitutional avoidance requires that route to be exhausted first \u2014 a fresh petition is not a second bite at the same evidentiary objection.",
  },
  {
    id: "chelete-credit-limited-v-office-of-the-data-prot",
    name: "Chelete Credit Limited v Office of the Data Protection Commissioner & Another",
    citation: "[2026] KEHC 8533",
    year: "2026",
    url: "https://dataprivacyadvocates.co.ke/case-chelete-credit-limited-v-office-of-the-data-prot.html",
    outcome: "Extension & injunction granted",
    categories: ["Data Protection", "Administrative Law"],
    summary: "The ODPC's notification emails about a KES 250,000 complaint had landed in the lender's spam folder \u2014 the company only found out about the determination when the complainant showed up demanding payment, by which point a Garnishee Order Nisi had already been served on Safaricom. Rather than treating the missed emails as the company's own administrative failure (as the complainant argued), the Court accepted spam filtering as a genuine, non-inordinate explanation for a 14-day delay, admitted the appeal out of time, and \u2014 because reputational and regulatory harm to a financial institution isn't fully cured by a later refund \u2014 froze the garnished funds pending appeal.",
    practicePoint: "Relying solely on email service without a parallel channel is now a live risk for the ODPC's own process, and a workable defence for respondents \u2014 but only if they can show they moved the moment they actually found out.",
  },
  {
    id: "githinji-v-muhindi-mweusi-supermarket-limited",
    name: "Githinji v Muhindi Mweusi Supermarket Limited",
    citation: "[2026] KEHC 7781",
    year: "2026",
    url: "https://dataprivacyadvocates.co.ke/case-githinji-v-muhindi-mweusi-supermarket-limited.html",
    outcome: "Claim dismissed",
    categories: ["Data Protection", "Administrative Law"],
    summary: "A former employee sued over the continued commercial use of her image on a supermarket's Facebook page and a billboard, alleging her signature on a consent letter had been forged and that she had never been paid for the advertising. The employer produced a signed consent letter and a WhatsApp message in which she had confirmed the final image was fine. The claim failed: allegations of fraud must be specifically pleaded and proved, and she had neither amended her pleadings to properly allege forgery nor called a handwriting expert to support it.",
    practicePoint: "The flip side of Matanta and Kipchirchir above: where a business can actually produce a signed consent letter and a contemporaneous approval message, the burden shifts back to the claimant \u2014 and a bare, unpleaded allegation of forgery will not be enough to unwind it.",
  },
  {
    id: "hair-manufacturing-limited-darling-kenya-v-kirum",
    name: "Hair Manufacturing Limited (Darling Kenya) v Kirumba",
    citation: "[2026] KEHC 1382",
    year: "2026",
    url: "https://dataprivacyadvocates.co.ke/case-hair-manufacturing-limited-darling-kenya-v-kirum.html",
    outcome: "Stay of execution granted",
    categories: ["Data Protection", "Administrative Law"],
    summary: "An appellant found liable by the Data Commissioner and ordered to pay Kshs 700,000 sought a stay of execution pending appeal. The complainant opposed the application as incompetent and argued no prejudice had been shown. The Court held the application was competent under Article 159(2)(d), that the appellant would suffer substantial loss absent a stay because there was no evidence the complainant was a person of means capable of refunding the decretal sum if the appeal succeeded, and that the appellant's prior deposit of Kshs 500,000 as security tipped the balance decisively in its favour.",
    practicePoint: "An early, voluntary deposit of security is doing real work in these stay applications \u2014 it demonstrates good faith and materially improves the odds of a stay being granted while an appeal against an ODPC award is pending.",
  },
  {
    id: "in-re-estate-of-samuel-kamau-nganga-deceased",
    name: "In re Estate of Samuel Kamau Nganga (Deceased)",
    citation: "[2026] KEHC 4183",
    year: "2026",
    url: "https://dataprivacyadvocates.co.ke/case-in-re-estate-of-samuel-kamau-nganga-deceased.html",
    outcome: "DNA application dismissed",
    categories: ["Data Protection", "Administrative Law"],
    summary: "In a succession matter, administrators sought a DNA test on a minor to establish paternity, pointing out the child's birth certificate had been issued eleven years after the alleged father's death. The widow opposed the test as an infringement of the minor's privacy. The Court agreed the DNA test was neither necessary nor proportionate: the operative legal question was whether the deceased son's own estate was entitled to a share of his father's estate \u2014 not whether the minor personally qualified as a beneficiary \u2014 and genetic data is sensitive personal data that compelled testing implicates both privacy and bodily integrity.",
    practicePoint: "Courts will not order DNA testing, which necessarily generates sensitive genetic data, where the legal question in dispute can be resolved without it. Frame succession or paternity disputes around the narrowest legal question actually in issue before reaching for genetic evidence.",
  },
  {
    id: "irungu-v-lintons-academy",
    name: "Irungu v Lintons Academy",
    citation: "[2026] KEHC 570",
    year: "2026",
    url: "https://dataprivacyadvocates.co.ke/case-irungu-v-lintons-academy.html",
    outcome: "Award adopted & enforced",
    categories: ["Data Protection", "Administrative Law"],
    summary: "Months after an ODPC award of KES 750,000 for unauthorised commercial use of a complainant's image, the respondent had filed an appeal but never prosecuted it \u2014 and never sought a stay. The Court adopted the ODPC's determination as a decree and granted leave to enforce it immediately, holding that Regulation 14(5) makes ODPC awards binding and enforceable as court orders, that an appeal does not automatically suspend enforcement under Order 42 Rule 6, and that a separate, express stay application is always required.",
    practicePoint: "An unpaid ODPC award plus an unprosecuted appeal is a live enforcement target \u2014 respondents who want breathing room must apply for a stay, not simply file and wait.",
  },
  {
    id: "kenya-airways-plc-v-obano",
    name: "Kenya Airways PLC v Obano",
    citation: "[2026] KEHC 7059",
    year: "2026",
    url: "https://dataprivacyadvocates.co.ke/case-kenya-airways-plc-v-obano.html",
    outcome: "Appeal allowed",
    categories: ["Data Protection", "Administrative Law"],
    summary: "A passenger's real grievance was that the airline failed to provide a wheelchair for his elderly mother; the data protection angle \u2014 a refused request for a recorded call \u2014 was secondary. The ODPC nonetheless proceeded to a KES 250,000 award while the airline's internal resolution process was still active, without waiting for that process to conclude. The Court confirmed that a voice recording is personal data and that access rights under Section 26 are real, but held that the Commissioner breached the doctrine of exhaustion by bypassing internal ADR, and that compensation under Section 65 needs actual proof of damage or distress \u2014 not just a technical violation. The determination was set aside in full as an overreach of the ODPC's mandate.",
    practicePoint: "A data-subject-access complaint is not a backdoor for the ODPC to adjudicate the underlying service dispute \u2014 and \"a right was violated\" is not, by itself, evidence of compensable harm.",
  },
  {
    id: "kipchirchir-v-hornbill-rongai-limited",
    name: "Kipchirchir v Hornbill Rongai Limited",
    citation: "[2026] KEHC 5928",
    year: "2026",
    url: "https://dataprivacyadvocates.co.ke/case-kipchirchir-v-hornbill-rongai-limited.html",
    outcome: "Damages & permanent injunction",
    categories: ["Data Protection", "Administrative Law"],
    summary: "An advocate's image and an accompanying caption were published on social media for commercial advertising without his consent. The business argued he had voluntarily posed for the photograph at its premises, where a general notice was displayed at the entrance. The Court held that a general notice at an entrance is not specific, informed consent to commercial use of a person's image, that the doctrine of exhaustion did not apply because the claim raised constitutional questions beyond the ODPC's reach, and that the unlawful dissemination was an intrusion into the plaintiff's private life under Articles 28 and 31. A separate defamation claim failed for lack of evidence that the plaintiff's reputation had actually been affected, but the privacy claim succeeded with a substantial damages award and a permanent injunction.",
    practicePoint: "A blanket notice at a venue entrance is not consent to use a visitor's image commercially \u2014 and a failed defamation claim does not drag down a well-evidenced privacy claim running alongside it.",
  },
  {
    id: "matanta-v-old-boma-limited-ta-saruni-basecamp",
    name: "Matanta v Old Boma Limited t/a Saruni Basecamp",
    citation: "[2026] KEHC 3053",
    year: "2026",
    url: "https://dataprivacyadvocates.co.ke/case-matanta-v-old-boma-limited-ta-saruni-basecamp.html",
    outcome: "Declarations, injunction & damages",
    categories: ["Data Protection", "Administrative Law"],
    summary: "Years after his employment ended, a former employee discovered his images still being used on the company's social media to advertise its business. The company argued he had given implied consent by participating in the original photoshoot. The Court held that consent to being photographed during employment does not extend to indefinite commercial use after termination absent clear authorisation, that the burden of proving consent for the continued use rested on the company (which produced no documentary evidence of it), and that privacy is not confined to intimate images \u2014 it extends to control over the commercial use of one's likeness. Damages and a permanent injunction followed.",
    practicePoint: "Consent obtained for one purpose, at one point in time, does not travel forward indefinitely. Employers who want to keep using an employee's image after they leave need a fresh, specific, documented authorisation to do so.",
  },
  {
    id: "mwaniki-v-safaricom-plc",
    name: "Mwaniki v Safaricom PLC",
    citation: "[2026] KEHC 8819",
    year: "2026",
    url: "https://dataprivacyadvocates.co.ke/case-mwaniki-v-safaricom-plc.html",
    outcome: "Suit struck out for non-exhaustion",
    categories: ["Data Protection", "Administrative Law"],
    summary: "A plaintiff sued Safaricom directly, alleging it had launched a financial product substantially identical to one he had developed and shared with the company, in violation of his data protection rights. Safaricom's preliminary objection argued the High Court lacked jurisdiction entirely, since data protection claims sit exclusively with the ODPC. The Court rejected that framing as \"mistaken and misconceived\": the High Court does have jurisdiction over data protection claims, but that jurisdiction is deferred, or staggered \u2014 the ODPC investigates and determines first, and the High Court's role follows, either on appeal or by adoption and enforcement of the resulting award. On the facts, the suit was struck out because the plaintiff had not gone to the ODPC first.",
    practicePoint: "Resist any argument that the ODPC's existence strips the High Court of jurisdiction altogether \u2014 the correct characterisation, now stated plainly by the Court, is a staggered jurisdiction where the ODPC goes first and the High Court's constitutional role remains fully intact, just deferred.",
  },
  {
    id: "odhiambo-and-another-v-attorney-general-and-anot",
    name: "Odhiambo & Another v Attorney General & Another",
    citation: "[2026] KEHC 3809",
    year: "2026",
    url: "https://dataprivacyadvocates.co.ke/case-odhiambo-and-another-v-attorney-general-and-anot.html",
    outcome: "Allowed in part \u2014 mandatory orders issued",
    categories: ["Data Protection", "Administrative Law"],
    summary: "Two prisoners challenged the unregulated reassignment of deactivated but previously registered mobile numbers, arguing such numbers constitute a person's digital identity and that mechanical reassignment after a period of inactivity \u2014 including inactivity caused by imprisonment \u2014 exposes personal information to third parties without any real safeguard. The Court agreed that a registered mobile number is a digital identifier attracting Article 31 protection, and that deactivation and reassignment without regard to a subscriber's circumstances poses a genuine privacy risk \u2014 while separately confirming that restricting prisoners' access to personal phones is itself a constitutional limitation. It ordered the Attorney General to develop safeguards against unfettered reassignment, with a default order that reassignment cease altogether if no regulatory scheme was implemented by a fixed deadline.",
    practicePoint: "This is the clearest judicial recognition yet that a mobile phone number is more than a communications tool \u2014 it is a digital identifier that Article 31 protects, and telcos and regulators should expect scrutiny of how recycled numbers are handled. It also sits alongside, and reinforces, the Taifa DT Sacco ruling in Volume I on who counts as a \"data subject\" when a number changes hands.",
  },
  {
    id: "onduko-v-squier-and-another",
    name: "Onduko v Squier & Another",
    citation: "[2026] KEHC 4642",
    year: "2026",
    url: "https://dataprivacyadvocates.co.ke/case-onduko-v-squier-and-another.html",
    outcome: "Declarations, injunctions & damages",
    categories: ["Data Protection", "Administrative Law"],
    summary: "A petitioner was subjected to persistent unwanted phone calls and messages, had images and video of her residence taken and circulated, and was discussed in a neighbourhood WhatsApp group created specifically about her, ostensibly over animal welfare concerns. The respondents argued this was a lawful, reasonable response to noise complaints and that the petitioner should have pursued alternative dispute resolution. The Court held the doctrines of exhaustion and constitutional avoidance did not bar the petition, that unauthorised surveillance and dissemination of material about a neighbour violated Articles 28 and 31, and awarded substantial compensation and permanent injunctions restraining further contact and filming \u2014 while dismissing a companion defamation claim for want of evidence.",
    practicePoint: "Privacy protection under Article 31 is not limited to data controllers and the ODPC's statutory framework \u2014 it reaches ordinary neighbour-to-neighbour surveillance, filming, and group messaging conducted outside any commercial or institutional context.",
  },
  {
    id: "otieno-v-university-of-nairobi-and-8-others",
    name: "Otieno v University of Nairobi & 8 Others",
    citation: "[2026] KEHC 4814",
    year: "2026",
    url: "https://dataprivacyadvocates.co.ke/case-otieno-v-university-of-nairobi-and-8-others.html",
    outcome: "Petition dismissed",
    categories: ["Data Protection", "Administrative Law"],
    summary: "A university employee alleged his phone had been accessed and the information used to terminate his employment, in violation of Articles 28 and 31. He had lodged a complaint with the Data Protection Commissioner \u2014 and then filed a constitutional petition on largely the same facts just four days later, before the ODPC's own 90-day statutory investigation window under Section 56(5) had even begun to run. The Court dismissed the petition, holding that running parallel proceedings on the same complaint amounted to forum shopping and offended both the doctrine of exhaustion and constitutional avoidance.",
    practicePoint: "Lodging an ODPC complaint and then filing a parallel constitutional petition before the ODPC has had a real opportunity to investigate is not a way to speed up relief \u2014 it is treated as forum shopping and risks losing both routes.",
  },
  {
    id: "ouko-v-independent-policing-oversight-authority",
    name: "Ouko v Independent Policing Oversight Authority",
    citation: "[2026] KEHC 7752",
    year: "2026",
    url: "https://dataprivacyadvocates.co.ke/case-ouko-v-independent-policing-oversight-authority.html",
    outcome: "Application dismissed",
    categories: ["Data Protection", "Administrative Law"],
    summary: "An applicant sought an order compelling Safaricom to produce his own certified call detail records, to test claims in an affidavit that he had been contacted. The Court confirmed that Section 26(b) of the Data Protection Act already gives a data subject the right to access their own personal data held by a data controller, without needing a court order at all \u2014 but dismissed the application because mandamus does not issue where an adequate alternative remedy exists, and the applicant had not shown he had ever actually asked Safaricom for the records and been refused.",
    practicePoint: "Before running to court for your own data, exercise the Section 26(b) access right directly with the data controller first \u2014 a court will not compel what you never actually requested.",
  },
  {
    id: "paprika-limited-v-office-of-the-data-protection",
    name: "Paprika Limited v Office of the Data Protection Commissioner & Another",
    citation: "[2026] KEHC 8168",
    year: "2026",
    url: "https://dataprivacyadvocates.co.ke/case-paprika-limited-v-office-of-the-data-protection.html",
    outcome: "Leave for judicial review denied",
    categories: ["Data Protection", "Administrative Law"],
    summary: "An employer used a staff member's likeness in promotional video under a term in his employment contract; after he absconded, he complained to the ODPC about the video's continued use. The employer sought judicial review of the resulting determination, but had already let its employee file a Section 64 appeal against the same decision \u2014 filed seven days before the judicial review application. The Court dismissed the judicial review bid on three independent grounds: an appellate remedy existed and hadn't been shown to be inadequate, running parallel proceedings against the same decision was an abuse of process, and \u2014 because the dispute was rooted in a contract of employment \u2014 the matter properly belonged before the Employment and Labour Relations Court, not the High Court, under Articles 162(2) and 165(5).",
    practicePoint: "Where personal data processing is bound up with an employment contract, check ELRC jurisdiction before filing anywhere else \u2014 and never run an appeal and a judicial review against the same determination at the same time.",
  },
  {
    id: "platinum-credit-limited-v-data-protection-commis",
    name: "Platinum Credit Limited v Data Protection Commissioner & Another",
    citation: "[2026] KEHC 7257",
    year: "2026",
    url: "https://dataprivacyadvocates.co.ke/case-platinum-credit-limited-v-data-protection-commis.html",
    outcome: "Appeal allowed",
    categories: ["Data Protection", "Administrative Law"],
    summary: "A lender's sales agent allegedly obtained a complainant's vehicle details from the company's own database and used them to cold-call him about a loan he had never sought. The ODPC investigated, found the agent had indeed accessed the data without consent, and ordered KES 400,000 in compensation plus a recommendation to prosecute the company's directors. On appeal, the fatal flaw was not the finding of liability \u2014 it was that the Commissioner relied on additional evidence from the sales agent that was never served on the lender, and never gave it a chance to cross-examine or rebut that evidence before deciding the case. The Court held that Articles 47 and 50 are \"the bedrock of Kenyan jurisprudence,\" not a technicality to be waived, and set the whole determination aside on that basis alone \u2014 while also flagging that KES 400,000 looked high absent proof of actual loss.",
    practicePoint: "If the ODPC relies on evidence a respondent has not seen \u2014 a witness statement, a site-visit note, an internal memo \u2014 that alone is enough to unwind the entire determination on appeal, regardless of how strong the underlying case looks.",
  },
  {
    id: "premier-credit-ltd-v-office-of-the-data-protecti",
    name: "Premier Credit Ltd v Office of the Data Protection Commissioner & Another",
    citation: "[2026] KEHC 9467",
    year: "2026",
    url: "https://dataprivacyadvocates.co.ke/case-premier-credit-ltd-v-office-of-the-data-protecti.html",
    outcome: "Partly allowed",
    categories: ["Data Protection", "Administrative Law"],
    summary: "Independent sales agents kept texting a woman who had formally asked to be removed from marketing lists, despite the lender's denial that her number was even in its system. The Court affirmed liability: agents acting within the scope of their delegated authority make the principal vicariously liable, and a lender that fails to produce its actual agency agreements can't complain when adverse inferences are drawn against it. But the Court also revised the KES 650,000 award down to KES 200,000, reasoning that an award pitched at a level that risks forcing closure of a smaller lender is punitive rather than compensatory, and out of step with prevailing economic conditions.",
    practicePoint: "Vicarious liability for agents is now settled law under the Act \u2014 but so is the principle that compensation must be evidence-based and proportionate to the size of the respondent, not maximalist by default.",
  },
  {
    id: "republic-v-komba",
    name: "Republic v Komba",
    citation: "[2026] KEHC 4850",
    year: "2026",
    url: "https://dataprivacyadvocates.co.ke/case-republic-v-komba.html",
    outcome: "Acquitted \u2014 no case to answer",
    categories: ["Criminal Law", "Digital Evidence"],
    summary: "Benson Amwai Komba was charged with the murder of Monica Wanjiru Ngatia at a lodging in Nyahururu in November 2023. At the close of the prosecution&rsquo;s case, the defence &mdash; through the firm of Muchangi Patrick &amp; Associates Advocates &mdash; filed a written no-case-to-answer submission that turned entirely on the reliability of the prosecution&rsquo;s digital evidence chain. The case against the Accused rested on a cellphone allegedly belonging to the deceased, tracked to a witness who claimed to have bought it from the Accused. But the officer who tracked the phone by its IMEI was never called to give evidence; no mobile network data was produced linking the phone&rsquo;s SIM history to the deceased; no forensic testing connected the device to her at all; and the witness who claimed to have purchased the phone had, by his own admission, no documentary proof of the transaction. The Court held that circumstantial evidence can only sustain a conviction where it &ldquo;irresistibly points to the Accused to the exclusion of all others&rdquo; &mdash; applying Sawe v Republic [2003] eKLR &mdash; and that an unbroken, evidenced chain from device to deceased to Accused is exactly what a phone-based prosecution case cannot skip. The prosecution&rsquo;s theory failed for want of that chain, and the Accused was acquitted at the close of the prosecution case under section 306(1) of the Criminal Procedure Code.",
    practicePoint: "A phone number is not evidence on its own &mdash; IMEI tracking, SIM registration and network records only carry weight if the officer who generated them testifies, and the technical chain from device to deceased is proved with data, not asserted from a witness&rsquo;s say-so. The same discipline that tests DNA or forensic chain-of-custody applies equally to mobile and digital evidence.",
  },
  {
    id: "republic-v-muthoni",
    name: "Republic v Muthoni",
    citation: "[2023] KEHC 17976",
    year: "2023",
    url: "https://dataprivacyadvocates.co.ke/case-republic-v-muthoni.html",
    outcome: "Acquitted \u2014 case not proved beyond reasonable doubt",
    categories: ["Criminal Law", "Evidence"],
    summary: "James Kimari Muthoni was charged with the murder of David Njoroge Kuria, stabbed outside a bar in Nyandarua County in 2014. The Accused was not arrested until 2018, after he returned to the area for a funeral. At trial, the prosecution called seven witnesses but produced no eyewitness to the stabbing itself, no forensic link between the alleged murder weapon and the Accused, and no identification parade &mdash; the investigating officer testified none was needed because &ldquo;the Accused was known.&rdquo; Cross-examining for the defence, counsel from Muchangi Patrick &amp; Associates Advocates drew out that every witness who placed the Accused near the incident was repeating what they had been told by others, not what they had seen; that the recovered knife, a common household item, was never forensically tested or linked to the Accused; and that the prosecution&rsquo;s own witnesses could not place the Accused and the Deceased together at the material time. The Court found the case rested entirely on circumstantial evidence and hearsay that fell well short of the standard set in Sawe v Republic [2003] eKLR and Abanga alias Onyango v Republic Cr. App. No. 32 of 1990 &mdash; that circumstantial evidence must form a chain so complete it excludes every hypothesis except guilt. It did not, and the Accused was acquitted.",
    practicePoint: "A four-year gap between offence and arrest, an unforensicated weapon, and witnesses who testify to what they were told rather than what they saw are not incidental weaknesses &mdash; cross-examined systematically, they are usually enough on their own to defeat a prosecution built on circumstantial evidence.",
  },
  {
    id: "republic-v-office-of-data-protection-commissione",
    name: "Republic v Office of Data Protection Commissioner; HS & 2 Others (Interested Parties); GEI & Another (Ex Parte Applicants)",
    citation: "[2026] KEHC 3987",
    year: "2026",
    url: "https://dataprivacyadvocates.co.ke/case-republic-v-office-of-data-protection-commissione.html",
    outcome: "Mandamus issued",
    categories: ["Data Protection", "Administrative Law"],
    summary: "The family of a minor wrongly identified as deceased in a newspaper photograph lodged a complaint; the ODPC acknowledged it, assigned a complaint number \u2014 and then went silent, well past the 90-day statutory determination window under Section 56(5). With no determination issued, the family had no appeal to file either. The Court found all eight classic conditions for mandamus satisfied and ordered the ODPC to admit the complaint within 10 days and issue a determination within 60 days of admission \u2014 a rare and pointed judicial rebuke of regulatory inertia.",
    practicePoint: "If the ODPC has acknowledged a complaint and gone silent past the 90-day mark, mandamus \u2014 not an appeal that doesn't yet exist \u2014 is the available remedy, and the statutory timeline is treated as mandatory, not aspirational.",
  },
  {
    id: "republic-v-office-of-the-data-protection-commiss",
    name: "Republic v Office of the Data Protection Commissioner; BVB Lounge (Ex Parte); EKM (Interested Party)",
    citation: "[2026] KEHC 114",
    year: "2026",
    url: "https://dataprivacyadvocates.co.ke/case-republic-v-office-of-the-data-protection-commiss.html",
    outcome: "Preliminary objection dismissed",
    categories: ["Data Protection", "Administrative Law"],
    summary: "The ODPC proceeded to determination on the mistaken premise that the applicant had never responded to a complaint, when in fact a response had been emailed weeks earlier. The regulator argued the applicant should have appealed under Section 64 instead of seeking judicial review. The Court drew a precise line: where a party has been heard but disputes the outcome, the statutory appeal is the route; where a party alleges it was never heard at all, that is an exceptional circumstance under Section 9(4) of the Fair Administrative Action Act that justifies bypassing the appeal mechanism entirely.",
    practicePoint: "\"I was heard but I disagree\" goes to appeal. \"I was never given the chance to be heard\" can go straight to judicial review \u2014 the distinction is the whole case.",
  },
  {
    id: "savla-v-maralal-energy-limited-and-2-others",
    name: "Savla v Maralal Energy Limited & 2 Others",
    citation: "[2026] KEHC 1281",
    year: "2026",
    url: "https://dataprivacyadvocates.co.ke/case-savla-v-maralal-energy-limited-and-2-others.html",
    outcome: "Declarations granted",
    categories: ["Data Protection", "Administrative Law"],
    summary: "A petitioner alleged systemic denial of access to his own salary and employment information, unauthorised use of his KRA PIN to file statutory returns, and non-compliance with binding directives of the Commission on Administrative Justice, all across three family-owned companies. The respondents argued the dispute was purely commercial and that the petitioner lacked capacity to sue. The Court held the burden of proving incapacity rested on the respondents and was not discharged by a single medical report, that the doctrine of constitutional avoidance did not apply because the primary claim was denial of information the petitioner had a constitutional right to access, that the right to information under Article 35 extends to private entities where needed to protect a right, and that using someone's KRA PIN to file statutory returns without their knowledge violates Article 31.",
    practicePoint: "Article 35 access-to-information rights are not confined to public bodies \u2014 and using a relative's or associate's statutory identifiers (KRA PIN, ID number) for filings without their knowledge is a live Article 31 privacy violation, separate from any data-controller relationship under the Act.",
  },
  {
    id: "savla-v-okonji",
    name: "Savla v Okonji",
    citation: "[2026] KEHC 9074",
    year: "2026",
    url: "https://dataprivacyadvocates.co.ke/case-savla-v-okonji.html",
    outcome: "Struck out",
    categories: ["Data Protection", "Administrative Law"],
    summary: "A petitioner alleged an unauthorised letter had been written about him in breach of Articles 10 and 31. The respondent's preliminary objection on locus standi, grounded in an allegation of mental incapacity, was disallowed on the basis that incapacity is a factual question requiring evidence, not a matter for a preliminary objection. The petition itself, however, was struck out on a separate, cleaner ground: clear statutory processes existed under the Mental Health Act, the Kenya Medical Practitioners and Dentists Act, and the Data Protection Act, all of which had to be exhausted before the constitutional door opened.",
    practicePoint: "A respondent cannot short-circuit a petition on disputed facts like capacity through a preliminary objection \u2014 but where multiple sector-specific statutory remedies exist and none has been tried, exhaustion will still dispose of the petition on a cleaner, undisputed ground.",
  },
  {
    id: "shah-v-shah-ta-john-cumming-and-company-and-anot",
    name: "Shah v Shah t/a John Cumming and Company & Another",
    citation: "[2026] KEHC 8674",
    year: "2026",
    url: "https://dataprivacyadvocates.co.ke/case-shah-v-shah-ta-john-cumming-and-company-and-anot.html",
    outcome: "Objection dismissed",
    categories: ["Data Protection", "Administrative Law"],
    summary: "A shareholding dispute turned on a recording of a meeting the objecting party had willingly attended; the objection invoked Article 31 and the Data Protection Act to keep it out. The Court held that an objector must actually demonstrate how their privacy was infringed \u2014 a bare invocation of the Act isn't enough \u2014 and that questions about how evidence was procured are for full trial, not a preliminary skirmish. It also noted, usefully, that the Act's Regulations only commenced on 14 January 2022, which matters for recordings made before then.",
    practicePoint: "A Data Protection Act objection to evidence needs a specific, demonstrated privacy harm \u2014 not just a citation to Article 31 \u2014 and timing matters if the recording predates the Regulations.",
  },
  {
    id: "taifa-dt-sacco-society-limited-v-otieno",
    name: "Taifa DT Sacco Society Limited v Otieno",
    citation: "[2026] KEHC 4944",
    year: "2026",
    url: "https://dataprivacyadvocates.co.ke/case-taifa-dt-sacco-society-limited-v-otieno.html",
    outcome: "Appeal allowed",
    categories: ["Data Protection", "Administrative Law"],
    summary: "A man who had never joined a SACCO kept receiving its credit and debit alerts after inheriting a recycled mobile number from an existing member. The ODPC ordered KES 250,000 in compensation for the SACCO's failure to stop the messages fast enough. The High Court reversed entirely: the complainant was not a data subject in respect of that number because no data of his was ever processed \u2014 only the original member's \u2014 and a month's delay in verifying a number reassignment the telco carried out without the SACCO's knowledge was reasonable, not a breach. The Court was blunt that the Act \"should not be used as a cash cow,\" warning against turning number-recycling inconvenience into a compensation industry.",
    practicePoint: "The person receiving unwanted messages is not automatically the \"data subject\" if no data about them was actually processed \u2014 and reasonable verification time before switching off a communication channel is a valid defence.",
  },
  {
    id: "thika-water-and-sewerage-company-limited-v-korir",
    name: "Thika Water & Sewerage Company Limited v Korir",
    citation: "[2026] KEHC 2725",
    year: "2026",
    url: "https://dataprivacyadvocates.co.ke/case-thika-water-and-sewerage-company-limited-v-korir.html",
    outcome: "Extension of time & stay granted",
    categories: ["Data Protection", "Administrative Law"],
    summary: "A public utility company sought leave to appeal an ODPC determination 21 days out of time, attributing the delay to its own public procurement process for hiring advocates. The complainant argued this was an unsupported internal administrative excuse. The Court accepted the explanation, taking judicial notice that public procurement for legal services genuinely takes time, held the 21-day delay was not inordinate, found the intended grounds of appeal arguable on both liability and quantum, and granted leave to appeal together with a stay \u2014 conditional on the appellant depositing the decretal amount in court.",
    practicePoint: "Public bodies bound by procurement law get real, judicially-noticed latitude on delay in appealing ODPC determinations \u2014 but a conditional deposit of the decretal sum remains the price of that latitude.",
  },
  {
    id: "tirito-v-murage-ta-murage-juma-and-company-advoc",
    name: "Tirito v Murage t/a Murage Juma and Company Advocates",
    citation: "[2026] KEHC 3998",
    year: "2026",
    url: "https://dataprivacyadvocates.co.ke/case-tirito-v-murage-ta-murage-juma-and-company-advoc.html",
    outcome: "Struck out",
    categories: ["Data Protection", "Administrative Law"],
    summary: "The petitioner alleged that his confidential travel documents had been unlawfully obtained and attached to court papers in an ELC suit, violating his privacy under Article 31 read with the Data Protection Act. The Court struck out the petition on two grounds: the advocate was acting as agent for his client, the actual plaintiff in the ELC suit, and had no personal liability for documents filed in that capacity; and the petition was, in substance, a belated attempt to challenge an evidentiary ruling already made in the ELC matter, dressed up as a constitutional question.",
    practicePoint: "Advocates acting for a client in litigation are not the correct respondents to a privacy petition arising from documents filed on the client's instructions \u2014 and courts will treat such petitions as impermissible collateral attacks on the underlying suit.",
  },
  {
    id: "tulia-amboseli-safari-camp-limited-v-opiyo-and-2",
    name: "Tulia Amboseli Safari Camp Limited v Opiyo & 2 Others",
    citation: "[2026] KEHC 3415",
    year: "2026",
    url: "https://dataprivacyadvocates.co.ke/case-tulia-amboseli-safari-camp-limited-v-opiyo-and-2.html",
    outcome: "Quantum reduced on appeal",
    categories: ["Data Protection", "Administrative Law"],
    summary: "A company that had acquired a going concern \u2014 including its website and digital assets \u2014 continued to display images of two former employees of the previous business for commercial promotion. The ODPC awarded each complainant Kshs 500,000. On appeal, the Court held that continued hosting and public display of the images was itself \"processing\" under the Act, that the acquiring company had produced no evidence of consent for that continued, post-acquisition use, and that consent given to the previous company did not automatically transfer to the new owner or extend to a new commercial purpose. The Court did, however, find the quantum excessive and reduced each award to Kshs 300,000, while confirming that the absence of an oral ODPC hearing had not itself denied the appellant a fair hearing.",
    practicePoint: "Buying a business as a going concern does not buy the consent that came with its old employees' images \u2014 due diligence on digital assets should specifically flag any personal data or images still in active commercial use.",
  },
  {
    id: "vihiga-college-of-business-and-technical-trainin",
    name: "Vihiga College of Business & Technical Training v Data Commissioner",
    citation: "[2026] KEHC 8304",
    year: "2026",
    url: "https://dataprivacyadvocates.co.ke/case-vihiga-college-of-business-and-technical-trainin.html",
    outcome: "Struck out",
    categories: ["Data Protection", "Administrative Law"],
    summary: "A small educational institution sought a stay of a Kshs 100,000 administrative fine for non-compliance with an ODPC Enforcement Notice, arguing immediate payment would severely strain its finances and that it had begun taking compliance steps. The Court found the statutory window to challenge the Penalty Notice had already lapsed by the time the application and appeal were filed, no formal application to extend time had been made, and that equitable considerations of hardship cannot be used to override a clear statute of limitation.",
    practicePoint: "Contrast this with Chelete Credit and Thika Water &amp; Sewerage above and in Volume I: courts will extend time for a credible, evidenced explanation, but financial hardship alone, raised without a properly filed application for extension, will not revive a lapsed statutory window.",
  },
  {
    id: "wangai-and-2-others-v-cabinet-secretary-ministry",
    name: "Wangai & 2 Others v Cabinet Secretary, Ministry of Information, Communications and the Digital Economy & 2 Others",
    citation: "[2026] KEHC 5690",
    year: "2026",
    url: "https://dataprivacyadvocates.co.ke/case-wangai-and-2-others-v-cabinet-secretary-ministry.html",
    outcome: "Allowed in part \u2014 structural interdict",
    categories: ["Data Protection", "Administrative Law"],
    summary: "Petitioners challenged the absence of any comprehensive AI policy, legislation or regulatory framework in Kenya, seeking conservatory orders restraining the deployment of \"high-risk artificial intelligence systems\" generally and drawing on the reasoning of the Huduma Namba litigation. The Court held the petition raised a genuine case for AI regulation, but that a vague, unparticularised moratorium on unnamed systems was unworkable and could not be granted as framed. Rather than dismiss the petition, the Court granted leave to amend it to identify specific AI systems, joined the Kenya National Commission on Human Rights as a necessary party, and adopted a structural interdict \u2014 ordering the respondents to file periodic situation reports on progress toward AI regulation, with a priority hearing date fixed.",
    practicePoint: "Kenya's courts will not issue broad, undefined restraining orders against \"AI\" as a category \u2014 petitions need to name the specific systems and harms in issue. But the structural interdict approach here signals active judicial oversight of AI regulation is coming, well ahead of any dedicated AI statute.",
  },
];

export const CASEBANK_BY_ID: Record<string, CasebankEntry> = Object.fromEntries(
  CASEBANK.map((c) => [c.id, c])
);
